#ifndef VISUALOBJECTS_VISUALOBJECTIDENTIFIERS_H
#define VISUALOBJECTS_VISUALOBJECTIDENTIFIERS_H

enum class VisualObjectID {
    Label,
    CircleNode,
    Arrow
};

#endif // VISUALOBJECTS_VISUALOBJECTIDENTIFIERS_H
